# Generated by Django 5.2.7 on 2025-11-05 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('ASSIGN', 'Assigned'), ('STATUS_CHANGE', 'Status Changed'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('EXPORT', 'Exported Data'), ('PAYMENT', 'Payment Action')], help_text='Type of action performed', max_length=20)),
                ('entity_type', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('BOOKING', 'Booking'), ('APPLICATION', 'Application'), ('PAYMENT', 'Payment'), ('EDIT_REQUEST', 'Edit Request'), ('USER', 'User'), ('DOCUMENT', 'Document'), ('SCHEME', 'Scheme'), ('SERVICE', 'Service')], help_text='Type of entity affected', max_length=20, null=True)),
                ('entity_id', models.PositiveIntegerField(blank=True, help_text='ID of the entity affected', null=True)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('old_value', models.TextField(blank=True, help_text='Previous value (for updates)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (for updates)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='activity_lo_user_id_711c04_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activity_lo_entity__456622_idx'), models.Index(fields=['action'], name='activity_lo_action_de9b3e_idx'), models.Index(fields=['-timestamp'], name='activity_lo_timesta_c26c07_idx')],
            },
        ),
    ]
