# Generated by Django 5.2.7 on 2025-11-05 08:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(help_text='Razorpay order ID', max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay payment ID (after successful payment)', max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay signature for verification', max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in INR', max_digits=10)),
                ('currency', models.CharField(default='INR', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partially Refunded')], default='PENDING', help_text='Payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Payment creation timestamp')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Successful payment timestamp', null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Refunded amount', max_digits=10)),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund', null=True)),
                ('refund_date', models.DateTimeField(blank=True, help_text='Refund processing date', null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method (UPI, Card, Net Banking, etc.)', max_length=50, null=True)),
                ('razorpay_response', models.JSONField(default=dict, help_text='Full Razorpay webhook response')),
                ('error_message', models.TextField(blank=True, help_text='Error message if payment failed', null=True)),
                ('booking', models.OneToOneField(help_text='Associated booking', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
                ('client', models.ForeignKey(help_text='Client making payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['razorpay_order_id'], name='payments_pa_razorpa_86ad18_idx'), models.Index(fields=['razorpay_payment_id'], name='payments_pa_razorpa_4059b1_idx'), models.Index(fields=['client', 'status'], name='payments_pa_client__39a683_idx'), models.Index(fields=['-created_at'], name='payments_pa_created_3147e3_idx')],
            },
        ),
    ]
