# Generated by Django 5.2.7 on 2025-11-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this payment', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof',
            field=models.FileField(blank=True, help_text='Optional proof/screenshot of payment', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='Sales employee who recorded/received this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, help_text='Transaction reference number (UTR/UPI Ref/Receipt No.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI_QR', 'UPI QR'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CARD', 'Card'), ('OTHER', 'Other')], help_text='Payment method/channel', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID (optional for offline/manual payments)', max_length=100, null=True),
        ),
    ]
