# Generated by Django 5.2.7 on 2025-11-05 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('clients', '0001_initial'),
        ('payments', '0002_payment_notes_payment_proof_payment_received_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_razorpa_86ad18_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_razorpa_4059b1_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_response',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='payment',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='When payment was approved', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager/Admin who approved this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if payment failed/disputed', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI_QR', 'UPI QR'), ('BANK_TRANSFER', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque/DD'), ('CARD', 'Card (POS/Swipe)'), ('OTHER', 'Other')], default='OTHER', help_text='Payment method/channel', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(help_text='Sales employee who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(default='', help_text='Transaction reference number (UTR/UPI Ref/Receipt No/Cheque No)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('CAPTURED', 'Payment Received'), ('FAILED', 'Failed/Disputed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_id'], name='payments_pa_referen_7b9331_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payments_pa_payment_5c92d7_idx'),
        ),
    ]
