# Generated by Django 4.2.7 on 2026-01-08 06:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_pending_amount_client_received_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_remove_razorpay_manual_payments_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pitched_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total pitched amount at time of recording', max_digits=12)),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Received amount at time of recording', max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pending amount at time of recording', max_digits=12)),
                ('source', models.CharField(choices=[('CLIENT_CREATION', 'Client Creation'), ('MANUAL_UPDATE', 'Manual Update'), ('PAYMENT_CAPTURED', 'Payment Captured'), ('OTHER', 'Other')], default='OTHER', help_text='Source/context of the revenue entry', max_length=30)),
                ('note', models.TextField(blank=True, help_text='Optional note or description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(help_text='Client associated with this revenue entry', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entries', to='clients.client')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_entries_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revenue Entry',
                'verbose_name_plural': 'Revenue Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='payments_re_client__c7ced2_idx'), models.Index(fields=['source'], name='payments_re_source_3b36d3_idx')],
            },
        ),
    ]
