# Generated by Django 5.2.7 on 2025-11-05 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('schemes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(editable=False, help_text='Auto-generated unique application ID', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to Government'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('ON_HOLD', 'On Hold')], default='DRAFT', help_text='Current application status', max_length=15)),
                ('applied_amount', models.DecimalField(decimal_places=2, help_text='Amount applied for (in lakhs)', max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved (in lakhs)', max_digits=12, null=True)),
                ('application_date', models.DateField(auto_now_add=True, help_text='Date when application was created')),
                ('submission_date', models.DateField(blank=True, help_text='Date when application was submitted to government', null=True)),
                ('approval_date', models.DateField(blank=True, help_text='Date when application was approved', null=True)),
                ('rejection_date', models.DateField(blank=True, help_text='Date when application was rejected', null=True)),
                ('documents_submitted', models.BooleanField(default=False, help_text='All required documents submitted')),
                ('purpose', models.TextField(help_text='Purpose/justification for the funding')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to client)', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True)),
                ('government_ref_number', models.CharField(blank=True, help_text='Government reference/acknowledgment number', max_length=100, null=True)),
                ('timeline', models.JSONField(default=list, help_text='Application status timeline with timestamps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Staff member handling this application', limit_choices_to={'role__in': ['ADMIN', 'MANAGER', 'SALES']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client making the application', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='clients.client')),
                ('created_by', models.ForeignKey(help_text='User who created this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_created', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(help_text='Scheme being applied to', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='schemes.scheme')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-application_date'],
                'indexes': [models.Index(fields=['application_id'], name='application_applica_2da665_idx'), models.Index(fields=['client', 'status'], name='application_client__133dd8_idx'), models.Index(fields=['scheme', 'status'], name='application_scheme__a1bf4b_idx'), models.Index(fields=['assigned_to', 'status'], name='application_assigne_7dbf8a_idx'), models.Index(fields=['-application_date'], name='application_applica_cff5d6_idx')],
                'unique_together': {('client', 'scheme', 'status')},
            },
        ),
    ]
