# Generated by Django 4.2.7 on 2026-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_replace_qr_with_barcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_employe_d91251_idx',
            old_name='employee_employee_id_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_status_d74ea5_idx',
            old_name='employee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_departm_9035da_idx',
            old_name='employee_department_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_created_d06e3b_idx',
            old_name='employee_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeverificationlog',
            new_name='employee_ve_employe_21834b_idx',
            old_name='employee_employee_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, editable=False, help_text='Auto-generated unique employee ID (e.g., 0101)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
