# Generated by Django 4.2.7 on 2025-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, help_text='Manual client name for Proforma', max_length=255),
        ),
    ]
