# Generated by Django 4.2.7 on 2025-11-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True, help_text='Full address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_contact_person',
            field=models.CharField(blank=True, help_text='Contact person name', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_gstin',
            field=models.CharField(blank=True, help_text='GSTIN (optional)', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_mobile',
            field=models.CharField(blank=True, help_text='Mobile/Phone', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
