# Generated by Django 4.2.7 on 2025-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_obsolete_amount_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item_description',
            field=models.TextField(help_text='Description of services/products'),
        ),
    ]
