# Generated by Django 5.2.7 on 2025-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Scheme name (e.g., CGTMSE, PMEGP)', max_length=200)),
                ('full_name', models.CharField(help_text='Full official name of the scheme', max_length=300)),
                ('scheme_code', models.CharField(help_text='Unique scheme code', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('LOAN', 'Loan/Credit Guarantee'), ('GRANT', 'Grant/Subsidy'), ('REGISTRATION', 'Registration/Certification'), ('SUBSIDY', 'Capital/Interest Subsidy'), ('TAX_BENEFIT', 'Tax Benefits')], help_text='Scheme category', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UPCOMING', 'Upcoming'), ('EXPIRED', 'Expired')], default='ACTIVE', help_text='Current scheme status', max_length=15)),
                ('description', models.TextField(help_text='Detailed scheme description')),
                ('benefits', models.TextField(help_text='Key benefits of the scheme')),
                ('eligible_sectors', models.JSONField(default=list, help_text='List of eligible business sectors')),
                ('eligible_business_types', models.JSONField(default=list, help_text='List of eligible business types (Pvt Ltd, LLP, etc.)')),
                ('min_turnover', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum annual turnover required (in lakhs)', max_digits=12, null=True)),
                ('max_turnover', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum annual turnover allowed (in lakhs)', max_digits=12, null=True)),
                ('min_company_age', models.IntegerField(blank=True, help_text='Minimum company age in years', null=True)),
                ('max_company_age', models.IntegerField(blank=True, help_text='Maximum company age in years', null=True)),
                ('min_funding', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum funding available (in lakhs)', max_digits=12, null=True)),
                ('max_funding', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum funding available (in lakhs)', max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate (if applicable)', max_digits=5, null=True)),
                ('subsidy_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Subsidy percentage (if applicable)', max_digits=5, null=True)),
                ('required_documents', models.JSONField(default=list, help_text='List of required documents')),
                ('official_website', models.URLField(blank=True, help_text='Official scheme website', null=True)),
                ('application_url', models.URLField(blank=True, help_text='Application portal URL', null=True)),
                ('processing_time_days', models.IntegerField(default=30, help_text='Expected processing time in days')),
                ('eligibility_notes', models.TextField(blank=True, help_text='Additional eligibility notes and conditions', null=True)),
                ('exclusion_criteria', models.TextField(blank=True, help_text='Cases where scheme is not applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['scheme_code'], name='schemes_sch_scheme__d384fb_idx'), models.Index(fields=['status', 'category'], name='schemes_sch_status_8dc638_idx')],
            },
        ),
    ]
