# Generated by Django 5.2.7 on 2025-11-05 08:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, help_text='Auto-generated unique client ID', max_length=20, unique=True)),
                ('company_name', models.CharField(help_text='Registered company/business name', max_length=200)),
                ('business_type', models.CharField(choices=[('PVT_LTD', 'Pvt Ltd Company'), ('LLP', 'LLP'), ('PROPRIETORSHIP', 'Proprietorship'), ('PARTNERSHIP', 'Partnership Firm'), ('OPC', 'One Person Company'), ('STARTUP', 'Startup'), ('NGO', 'NGO'), ('SECTION_8', 'Section 8 (Schools, Hospitals, etc.)'), ('OTHER', 'Other')], help_text='Type of business entity', max_length=20)),
                ('sector', models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('SERVICE', 'Service'), ('RETAIL', 'Retail/Trading'), ('IT_SOFTWARE', 'IT/Software'), ('AGRICULTURE', 'Agriculture'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('FOOD_BEVERAGE', 'Food & Beverage'), ('CONSTRUCTION', 'Construction'), ('TEXTILE', 'Textile'), ('CHEMICAL', 'Chemical'), ('PHARMA', 'Pharma'), ('LOGISTICS', 'Logistics'), ('OTHER', 'Other')], help_text='Primary business sector', max_length=20)),
                ('company_age', models.IntegerField(help_text='Age of company in years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('registration_number', models.CharField(blank=True, help_text='Company registration number (CIN/LLPIN/etc.)', max_length=50, null=True)),
                ('gst_number', models.CharField(blank=True, help_text='GST registration number', max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, help_text='Company PAN number', max_length=10, null=True)),
                ('annual_turnover', models.DecimalField(decimal_places=2, help_text='Annual turnover in lakhs', max_digits=12)),
                ('funding_required', models.DecimalField(decimal_places=2, help_text='Total funding required in lakhs', max_digits=12)),
                ('existing_loans', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Existing loan amount in lakhs', max_digits=12)),
                ('contact_person', models.CharField(help_text='Primary contact person name', max_length=200)),
                ('contact_email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('contact_phone', models.CharField(help_text='Primary contact phone', max_length=15)),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate contact phone', max_length=15, null=True)),
                ('address_line1', models.CharField(help_text='Address line 1', max_length=200)),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2', max_length=200, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State', max_length=100)),
                ('pincode', models.CharField(help_text='Pincode', max_length=6)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING_DOCS', 'Pending Documents'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='ACTIVE', help_text='Current client status', max_length=20)),
                ('business_description', models.TextField(blank=True, help_text='Brief description of business activities', null=True)),
                ('funding_purpose', models.TextField(blank=True, help_text='Purpose of funding requirement', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to client)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when client was registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('assigned_manager', models.ForeignKey(blank=True, help_text='Manager overseeing this client', limit_choices_to={'role__in': ['ADMIN', 'MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients_manager', to=settings.AUTH_USER_MODEL)),
                ('assigned_sales', models.ForeignKey(help_text='Sales employee assigned to this client', limit_choices_to={'role': 'SALES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients_sales', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this client record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Associated user account for client login', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_id'], name='clients_cli_client__a44f5d_idx'), models.Index(fields=['company_name'], name='clients_cli_company_9dfa94_idx'), models.Index(fields=['assigned_sales', 'status'], name='clients_cli_assigne_3e0166_idx'), models.Index(fields=['sector', 'annual_turnover'], name='clients_cli_sector_97ce8c_idx')],
            },
        ),
    ]
