# Generated by Django 4.2.7 on 2025-11-13 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_client_approval_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Generated username', max_length=150)),
                ('email', models.EmailField(help_text='Client email', max_length=254)),
                ('plain_password', models.CharField(help_text='Plain text password (only stored once)', max_length=100)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether credentials have been sent to client')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When credentials were sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(help_text='Client these credentials belong to', on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='clients.client')),
                ('created_by', models.ForeignKey(help_text='Who created this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials_created', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, help_text='Who sent the credentials', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Credential',
                'verbose_name_plural': 'Client Credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
