# Generated by Django 4.2.7 on 2025-11-13 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Address line 1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='annual_turnover',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual turnover in lakhs', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_type',
            field=models.CharField(blank=True, choices=[('PVT_LTD', 'Pvt Ltd Company'), ('LLP', 'LLP'), ('PROPRIETORSHIP', 'Proprietorship'), ('PARTNERSHIP', 'Partnership Firm'), ('OPC', 'One Person Company'), ('STARTUP', 'Startup'), ('NGO', 'NGO'), ('SECTION_8', 'Section 8 (Schools, Hospitals, etc.)'), ('OTHER', 'Other')], help_text='Type of business entity', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_age',
            field=models.IntegerField(blank=True, help_text='Age of company in years', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='funding_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total funding required in lakhs', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pincode',
            field=models.CharField(blank=True, help_text='Pincode', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sector',
            field=models.CharField(blank=True, choices=[('MANUFACTURING', 'Manufacturing'), ('SERVICE', 'Service'), ('RETAIL', 'Retail/Trading'), ('IT_SOFTWARE', 'IT/Software'), ('AGRICULTURE', 'Agriculture'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('FOOD_BEVERAGE', 'Food & Beverage'), ('CONSTRUCTION', 'Construction'), ('TEXTILE', 'Textile'), ('CHEMICAL', 'Chemical'), ('PHARMA', 'Pharma'), ('LOGISTICS', 'Logistics'), ('OTHER', 'Other')], help_text='Primary business sector', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100, null=True),
        ),
    ]
