# Generated by Django 4.2.7 on 2026-01-08 06:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pending amount (₹) expected from client', max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount (₹) received so far from client', max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='total_pitched_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total pitched amount (₹) discussed with client', max_digits=12),
        ),
    ]
