# Generated by Django 4.2.7 on 2026-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_fix_utf8mb4_charset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sector',
            field=models.CharField(blank=True, choices=[('MANUFACTURING', 'Manufacturing'), ('SERVICE', 'Service'), ('RETAIL', 'Retail/Trading'), ('IT_SOFTWARE', 'IT/Software'), ('AGRICULTURE', 'Agriculture'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('FOOD_BEVERAGE', 'Food & Beverage'), ('CONSTRUCTION', 'Construction'), ('TEXTILE', 'Textile'), ('CHEMICAL', 'Chemical'), ('PHARMA', 'Pharma'), ('LOGISTICS', 'Logistics'), ('NGO_SOCIAL', 'NGO/Social Work'), ('NGO_CHARITY', 'Charity/Welfare'), ('NGO_ENVIRONMENT', 'Environment/Conservation'), ('NGO_HEALTH', 'Health & Sanitation'), ('NGO_EDUCATION', 'Education & Literacy'), ('NGO_WOMEN', 'Women Empowerment'), ('NGO_CHILD', 'Child Welfare'), ('OTHER', 'Other')], help_text='Primary business sector', max_length=20, null=True),
        ),
    ]
