# Generated by Django 5.2.7 on 2025-11-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Marks this Admin as the company owner for special dashboard access'),
        ),
    ]
