# Generated by Django 5.2.7 on 2025-11-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_cookie_age', models.PositiveIntegerField(default=86400, help_text='Session lifetime in seconds (e.g., 86400 = 1 day).')),
                ('session_expire_at_browser_close', models.BooleanField(default=False, help_text='Expire session when browser closes (overrides cookie age).')),
                ('session_idle_timeout', models.PositiveIntegerField(default=1800, help_text='Auto logout after this many seconds of inactivity (0 to disable).')),
                ('session_cookie_secure', models.BooleanField(default=False, help_text='Mark session cookie as Secure (HTTPS only). Enable in production over HTTPS.')),
                ('csrf_cookie_secure', models.BooleanField(default=False, help_text='Mark CSRF cookie as Secure (HTTPS only). Enable in production over HTTPS.')),
                ('secure_ssl_redirect', models.BooleanField(default=False, help_text='Redirect all HTTP requests to HTTPS (requires proxy/HTTPS).')),
                ('secure_hsts_seconds', models.PositiveIntegerField(default=0, help_text='HSTS max-age in seconds (0 disables). Enable with caution in production.')),
                ('secure_hsts_include_subdomains', models.BooleanField(default=False, help_text='Include subdomains in HSTS policy.')),
                ('secure_hsts_preload', models.BooleanField(default=False, help_text='Enable HSTS preload (submit domain to browser preload lists).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
