# Generated by Django 4.2.7 on 2025-11-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser'), ('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SALES', 'Sales Employee'), ('CLIENT', 'Client')], default='CLIENT', help_text='User role determines access permissions', max_length=10),
        ),
    ]
