# Generated by Django 5.2.7 on 2025-11-05 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('bookings', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DPR', 'Detailed Project Report'), ('PITCH_DECK', 'Pitch Deck'), ('FINANCIAL_PROJECTION', 'Financial Projections'), ('FUND_UTILIZATION', 'Fund Utilisation Report'), ('APPLICATION_FORM', 'Scheme Application Form'), ('CERTIFICATE', 'Certificate/Registration'), ('INVOICE', 'Invoice/Receipt'), ('OTHER', 'Other Document')], help_text='Type of document', max_length=25)),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Document description', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SENT', 'Sent to Client'), ('DOWNLOADED', 'Downloaded by Client')], default='DRAFT', help_text='Document status', max_length=15)),
                ('file', models.FileField(help_text='Uploaded/generated document file', upload_to='documents/%Y/%m/')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('file_format', models.CharField(default='PDF', help_text='File format (PDF, DOCX, etc.)', max_length=10)),
                ('template_used', models.CharField(blank=True, help_text='Template used for generation', max_length=100, null=True)),
                ('generation_data', models.JSONField(default=dict, help_text='Data used for document generation')),
                ('download_count', models.IntegerField(default=0, help_text='Number of times document was downloaded')),
                ('last_downloaded_at', models.DateTimeField(blank=True, help_text='Last download timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, help_text='Associated application (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.application')),
                ('booking', models.ForeignKey(blank=True, help_text='Associated booking (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='bookings.booking')),
                ('client', models.ForeignKey(help_text='Client this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('generated_by', models.ForeignKey(help_text='User who generated/uploaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_generated', to=settings.AUTH_USER_MODEL)),
                ('last_downloaded_by', models.ForeignKey(blank=True, help_text='User who last downloaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_downloaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'document_type'], name='documents_d_client__ff88a6_idx'), models.Index(fields=['application'], name='documents_d_applica_bd788a_idx'), models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx')],
            },
        ),
    ]
