# Generated by Django 4.2.7 on 2025-11-13 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_approval_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('DPR', 'Detailed Project Report (DPR)'), ('PITCH_DECK', 'Pitch Deck'), ('FINANCIAL_PROJECTION', 'Financial Projections'), ('FUND_UTILIZATION', 'Fund Utilisation Report'), ('AGREEMENT', 'Agreement/Contract'), ('COMPANY_REG', 'Company Registration Certificate'), ('GST_CERT', 'GST Registration Certificate'), ('PAN_CARD', 'PAN Card'), ('MSME_CERT', 'MSME/Udyam Registration'), ('BANK_STATEMENT', 'Bank Statements (6 months)'), ('ITR', 'Income Tax Returns (Last 2 years)'), ('BALANCE_SHEET', 'Balance Sheet & P&L'), ('INCORPORATION_CERT', 'Certificate of Incorporation'), ('MOA_AOA', 'MOA & AOA'), ('BOARD_RESOLUTION', 'Board Resolution'), ('APPLICATION_FORM', 'Scheme Application Form'), ('INVOICE', 'Invoice/Receipt'), ('OTHER', 'Other Document')], help_text='Type of document', max_length=25),
        ),
        migrations.CreateModel(
            name='DocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DPR', 'Detailed Project Report (DPR)'), ('PITCH_DECK', 'Pitch Deck'), ('FINANCIAL_PROJECTION', 'Financial Projections'), ('FUND_UTILIZATION', 'Fund Utilisation Report'), ('AGREEMENT', 'Agreement/Contract'), ('COMPANY_REG', 'Company Registration Certificate'), ('GST_CERT', 'GST Registration Certificate'), ('PAN_CARD', 'PAN Card'), ('MSME_CERT', 'MSME/Udyam Registration'), ('BANK_STATEMENT', 'Bank Statements (6 months)'), ('ITR', 'Income Tax Returns (Last 2 years)'), ('BALANCE_SHEET', 'Balance Sheet & P&L'), ('INCORPORATION_CERT', 'Certificate of Incorporation'), ('MOA_AOA', 'MOA & AOA'), ('BOARD_RESOLUTION', 'Board Resolution'), ('APPLICATION_FORM', 'Scheme Application Form'), ('INVOICE', 'Invoice/Receipt'), ('OTHER', 'Other Document')], help_text='Type of required document', max_length=25)),
                ('is_required', models.BooleanField(default=True, help_text='Is this document mandatory?')),
                ('is_uploaded', models.BooleanField(default=False, help_text='Has client uploaded this document?')),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes for this document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client for this checklist', on_delete=django.db.models.deletion.CASCADE, related_name='document_checklist', to='clients.client')),
                ('created_by', models.ForeignKey(help_text='Sales employee who created this checklist item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_created', to=settings.AUTH_USER_MODEL)),
                ('uploaded_document', models.ForeignKey(blank=True, help_text='Link to uploaded document if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Checklist Item',
                'verbose_name_plural': 'Document Checklist Items',
                'ordering': ['client', 'is_required', 'document_type'],
                'indexes': [models.Index(fields=['client', 'is_uploaded'], name='documents_d_client__6f27a8_idx'), models.Index(fields=['client', 'is_required'], name='documents_d_client__411357_idx')],
                'unique_together': {('client', 'document_type')},
            },
        ),
    ]
