# Generated by Django 4.2.7 on 2026-01-28 07:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0011_alter_client_sector'),
        ('employees', '0003_rename_employee_employee_id_idx_employee_employe_d91251_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('agreement_type', models.CharField(choices=[('funding', 'Funding Agreement'), ('website', 'Website Agreement')], max_length=20)),
                ('service_receiver_name', models.CharField(help_text='Name of Service Receiver', max_length=255)),
                ('service_receiver_address', models.TextField(help_text='Complete Address')),
                ('date_of_agreement', models.DateField(help_text='Date of Agreement')),
                ('service_description', models.TextField(help_text='Description of Service')),
                ('total_amount_pitched', models.DecimalField(decimal_places=2, help_text='Total Amount Pitched', max_digits=12)),
                ('received_amount_stage1', models.DecimalField(decimal_places=2, help_text='Received Amount without GST (Stage 1)', max_digits=12)),
                ('pending_amount_stage2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Pending Amount (Stage 2) - Optional', max_digits=12, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Commission Percentage after Disbursement', max_digits=5)),
                ('commission_stage', models.CharField(choices=[('stage_1', 'Stage 1 - Received'), ('stage_2', 'Stage 2 - Pending/Commission'), ('stage_3', 'Stage 3 - Final Commission')], default='stage_2', help_text='Stage when commission applies', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreements', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee handling this agreement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
                'ordering': ['-created_at'],
            },
        ),
    ]
