# Generated by Django 4.2.7 on 2026-01-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='service_receiver_designation',
            field=models.CharField(default='Director', help_text='Designation of Service Receiver (e.g., Director, Proprietor)', max_length=100),
        ),
    ]
