# Generated by Django 4.2.7 on 2026-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreement_service_receiver_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='service_receiver_designation',
            field=models.CharField(choices=[('Representative', 'Representative'), ('Director', 'Director'), ('Proprietor', 'Proprietor'), ('CEO', 'CEO'), ('Managing Director', 'Managing Director'), ('Partner', 'Partner'), ('Other', 'Other (Specify in Notes)')], default='Representative', help_text='Designation of Service Receiver', max_length=100),
        ),
    ]
