# Generated by Django 4.2.7 on 2025-11-13 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_approval_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemes', '0001_initial'),
        ('documents', '0002_alter_document_document_type_documentchecklist'),
        ('applications', '0002_remove_unique_constraint'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('WEB_DEVELOPMENT', 'Website Development'), ('DIGITAL_MARKETING', 'Digital Marketing'), ('CERTIFICATION', 'Business Certifications'), ('CONSULTING', 'Business Consulting'), ('BRANDING', 'Branding & Design'), ('TRAINING', 'Training & Workshops'), ('LEGAL', 'Legal Services'), ('ACCOUNTING', 'Accounting & Taxation'), ('IT_SUPPORT', 'IT Support'), ('OTHER', 'Other Services')], help_text='Type of service', max_length=20)),
                ('name', models.CharField(help_text='Service name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('short_description', models.CharField(blank=True, help_text='Short description for cards/listings', max_length=300)),
                ('pricing_type', models.CharField(choices=[('FIXED', 'Fixed Price'), ('HOURLY', 'Hourly Rate'), ('PROJECT', 'Project Based'), ('CUSTOM', 'Custom Quote')], default='CUSTOM', help_text='Pricing model', max_length=20)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price (if applicable)', max_digits=10, null=True)),
                ('key_features', models.JSONField(default=list, help_text='List of key features/deliverables')),
                ('is_active', models.BooleanField(default=True, help_text='Is this service currently offered?')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured services?')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display (lower = higher)')),
                ('icon', models.CharField(default='bi-briefcase', help_text='Bootstrap icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Offering',
                'verbose_name_plural': 'Service Offerings',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientServiceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('INTERESTED', 'Interested'), ('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RECOMMENDED', help_text='Enrollment status', max_length=15)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed price for this service', max_digits=10, null=True)),
                ('enrolled_at', models.DateField(blank=True, help_text='When client enrolled', null=True)),
                ('expected_completion', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('completed_at', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client enrolled in service', on_delete=django.db.models.deletion.CASCADE, related_name='service_enrollments', to='clients.client')),
                ('recommended_by', models.ForeignKey(help_text='Sales who recommended this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_recommended', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service offered', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tracking.serviceoffering')),
            ],
            options={
                'verbose_name': 'Client Service Enrollment',
                'verbose_name_plural': 'Client Service Enrollments',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_UNDER_REVIEW', 'Application Under Review'), ('DOCUMENTS_REQUESTED', 'Documents Requested'), ('DOCUMENTS_RECEIVED', 'Documents Received'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('MILESTONE_ACHIEVED', 'Milestone Achieved'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('MEETING_COMPLETED', 'Meeting Completed'), ('TASK_ASSIGNED', 'Task Assigned to Client'), ('TASK_COMPLETED', 'Task Completed'), ('SERVICE_RECOMMENDED', 'Service Recommended'), ('SERVICE_ENROLLED', 'Service Enrolled'), ('SCHEME_RECOMMENDED', 'Scheme Recommended'), ('SCHEME_APPLIED', 'Applied for Scheme'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_PENDING', 'Payment Pending'), ('GENERAL_UPDATE', 'General Update'), ('IMPORTANT_NOTICE', 'Important Notice')], help_text='Type of activity/update', max_length=30)),
                ('title', models.CharField(help_text='Activity title (shown in timeline)', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the activity', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level', max_length=10)),
                ('is_visible_to_client', models.BooleanField(default=True, help_text='Should this be visible to the client?')),
                ('due_date', models.DateField(blank=True, help_text='Due date (for tasks)', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the activity was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to client)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, help_text='Related application (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='applications.application')),
                ('booking', models.ForeignKey(blank=True, help_text='Related booking (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='bookings.booking')),
                ('client', models.ForeignKey(help_text='Client this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clients.client')),
                ('created_by', models.ForeignKey(help_text='Sales/User who created this update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, help_text='Related document (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='documents.document')),
                ('scheme', models.ForeignKey(blank=True, help_text='Related scheme (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='schemes.scheme')),
                ('service_offering', models.ForeignKey(blank=True, help_text='Related service offering (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tracking.serviceoffering')),
            ],
            options={
                'verbose_name': 'Client Activity',
                'verbose_name_plural': 'Client Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='tracking_cl_client__1ee26d_idx'), models.Index(fields=['client', 'is_visible_to_client', '-created_at'], name='tracking_cl_client__ecb9f8_idx'), models.Index(fields=['status', '-created_at'], name='tracking_cl_status_1b6cf6_idx'), models.Index(fields=['activity_type'], name='tracking_cl_activit_6083a3_idx')],
            },
        ),
    ]
