# Generated by Django 5.2.7 on 2025-11-05 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('CLIENT', 'Client'), ('BOOKING', 'Booking'), ('APPLICATION', 'Application'), ('USER', 'User')], help_text='Type of entity being edited', max_length=20)),
                ('entity_id', models.IntegerField(help_text='ID of the entity being edited')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied Successfully')], default='PENDING', help_text='Request status', max_length=15)),
                ('field_name', models.CharField(help_text='Name of the field to be changed', max_length=100)),
                ('current_value', models.TextField(blank=True, help_text='Current value of the field', null=True)),
                ('requested_value', models.TextField(help_text='Requested new value')),
                ('reason', models.TextField(help_text='Reason for requesting the change')),
                ('approval_notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection', null=True)),
                ('approval_date', models.DateTimeField(blank=True, help_text='Date when request was approved/rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Request creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved/rejected the request', limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='User who made the request', on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edit Request',
                'verbose_name_plural': 'Edit Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='edit_reques_entity__920989_idx'), models.Index(fields=['status', '-created_at'], name='edit_reques_status_8f2698_idx'), models.Index(fields=['requested_by', 'status'], name='edit_reques_request_a59189_idx')],
            },
        ),
    ]
