# Generated by Django 5.2.7 on 2025-11-05 08:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name', max_length=200)),
                ('category', models.CharField(choices=[('FUNDING', 'Funding Services'), ('INCORPORATION', 'Incorporation Services'), ('CERTIFICATION', 'Certification Services'), ('GROWTH', 'Growth Services'), ('CSR', 'CSR Services'), ('CONSULTING', 'Consulting Services')], help_text='Service category', max_length=20)),
                ('description', models.TextField(help_text='Detailed service description')),
                ('short_description', models.TextField(help_text='Brief service description (for listings)', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration_days', models.IntegerField(default=30, help_text='Expected completion duration in days')),
                ('is_active', models.BooleanField(default=True, help_text='Service is active and available for booking')),
                ('features', models.JSONField(default=list, help_text='List of features included in service')),
                ('deliverables', models.JSONField(default=list, help_text='List of deliverables for this service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='bookings_se_categor_d04f0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, help_text='Auto-generated unique booking ID', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid - In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current booking status', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Booking priority level', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Booking amount in INR', max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage applied', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Final amount after discount', max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True, help_text='Date when booking was created')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date when payment was completed', null=True)),
                ('expected_completion_date', models.DateField(blank=True, help_text='Expected service completion date', null=True)),
                ('actual_completion_date', models.DateField(blank=True, help_text='Actual service completion date', null=True)),
                ('requirements', models.TextField(blank=True, help_text='Client requirements and specifications', null=True)),
                ('progress_percent', models.IntegerField(default=0, help_text='Completion progress percentage', validators=[django.core.validators.MinValueValidator(0)])),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to client)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to fulfill booking', limit_choices_to={'role__in': ['ADMIN', 'MANAGER', 'SALES']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='Client who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clients.client')),
                ('created_by', models.ForeignKey(help_text='User who created this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service booked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.service')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date'],
                'indexes': [models.Index(fields=['booking_id'], name='bookings_bo_booking_eb8fc3_idx'), models.Index(fields=['client', 'status'], name='bookings_bo_client__09b1d6_idx'), models.Index(fields=['assigned_to', 'status'], name='bookings_bo_assigne_9143d2_idx'), models.Index(fields=['-booking_date'], name='bookings_bo_booking_d0de6b_idx')],
            },
        ),
    ]
