# Generated by Django 4.2.7 on 2026-01-14 05:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_service_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST amount (auto-calculated)', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST percentage for this booking', max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pending amount for this booking', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='pitched_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pitched amount for this booking (excluding GST)', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received for this booking', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_with_gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount including GST for this booking', max_digits=12),
        ),
    ]
