# Generated by Django 4.2.7 on 2026-01-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_gst_amount_booking_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid - In Progress'), ('DOCUMENT_COLLECTION', 'Awaiting Documents'), ('ACTIVE', 'Active - In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current booking status', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('COMPANY_REG', 'Company Registration Certificate'), ('GST_CERT', 'GST Registration Certificate'), ('PAN_CARD', 'PAN Card'), ('MSME_CERT', 'MSME/Udyam Registration'), ('BANK_STATEMENT', 'Bank Statements (6 months)'), ('ITR', 'Income Tax Returns (Last 2 years)'), ('BALANCE_SHEET', 'Balance Sheet & P&L'), ('INCORPORATION_CERT', 'Certificate of Incorporation'), ('MOA_AOA', 'MOA & AOA'), ('BOARD_RESOLUTION', 'Board Resolution'), ('APPLICATION_FORM', 'Scheme Application Form'), ('OTHER', 'Other Document')], help_text='Type of document required', max_length=25)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this document is mandatory for service completion')),
                ('description', models.TextField(blank=True, help_text='Description of why this document is needed')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display in the form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='Service this requirement applies to', on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='bookings.service')),
            ],
            options={
                'verbose_name': 'Service Document Requirement',
                'verbose_name_plural': 'Service Document Requirements',
                'ordering': ['service', 'display_order'],
                'indexes': [models.Index(fields=['service', 'is_mandatory'], name='bookings_se_service_7fcc43_idx')],
                'unique_together': {('service', 'document_type')},
            },
        ),
    ]
