# Generated by Django 5.2.7 on 2025-11-05 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('bookings', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('BOTH', 'Email + WhatsApp')], help_text='Communication channel', max_length=10)),
                ('notification_type', models.CharField(choices=[('WELCOME', 'Welcome Message'), ('CREDENTIALS', 'Login Credentials'), ('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('DOCUMENT_READY', 'Document Ready for Download'), ('EDIT_REQUEST_APPROVED', 'Edit Request Approved'), ('EDIT_REQUEST_REJECTED', 'Edit Request Rejected'), ('REMINDER', 'Reminder/Follow-up'), ('CUSTOM', 'Custom Message')], help_text='Type of notification', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent Successfully'), ('FAILED', 'Failed'), ('QUEUED', 'Queued for Sending')], default='PENDING', help_text='Notification status', max_length=10)),
                ('subject', models.CharField(help_text='Email subject or WhatsApp message title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('html_content', models.TextField(blank=True, help_text='HTML content for email (optional)', null=True)),
                ('email_to', models.EmailField(blank=True, help_text='Recipient email address', max_length=254, null=True)),
                ('whatsapp_to', models.CharField(blank=True, help_text='Recipient WhatsApp number', max_length=15, null=True)),
                ('attachments', models.JSONField(default=list, help_text='List of attachment file paths')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was sent', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='Timestamp when notification failed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if notification failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('email_message_id', models.CharField(blank=True, help_text='Email message ID from SMTP server', max_length=200, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='WhatsApp message ID from API', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='User/client who will receive the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, help_text='Related application (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='applications.application')),
                ('related_booking', models.ForeignKey(blank=True, help_text='Related booking (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('related_payment', models.ForeignKey(blank=True, help_text='Related payment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.payment')),
                ('sent_by', models.ForeignKey(blank=True, help_text='User who triggered the notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'), models.Index(fields=['notification_type', 'status'], name='notificatio_notific_a659f1_idx'), models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx')],
            },
        ),
    ]
